services:
  postgres:
    image: postgres:latest
    container_name: nexus-postgres
    environment:
      POSTGRES_DB: nexus
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  neo4j:
    image: neo4j:latest
    container_name: nexus-neo4j
    environment:
      NEO4J_AUTH: neo4j/password123
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_logs:/logs
      - neo4j_config:/config
      - neo4j_data:/data
      - neo4j_plugins:/plugins
    restart: always

volumes:
  postgres_data:
  neo4j_logs:
  neo4j_config:
  neo4j_data:
  neo4j_plugins:
